# Generated by Django 5.2.1 on 2025-08-07 09:59

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('description', models.TextField(max_length=2000, verbose_name='توضیع')),
                ('create_at', django_jalali.db.models.jDateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='محصول', to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='کاربر', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
