# Generated by Django 5.2.1 on 2025-08-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
