# Generated by Django 5.2.1 on 2025-07-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'گالری'},
        ),
    ]
