# Generated by Django 5.2.1 on 2025-06-07 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_product_products_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 7, 8, 3, 5, 872207)),
        ),
    ]
