# Generated by Django 5.2.1 on 2025-06-21 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('50%', '50%')], default='0%', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 9, 45, 23, 213628)),
        ),
    ]
