# Generated by Django 5.2.1 on 2025-06-21 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_date_alter_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 10, 39, 26, 68307)),
        ),
    ]
