# Generated by Django 5.2.1 on 2025-08-07 09:53

import authentication.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_image, verbose_name='عکس')),
                ('date_modefied', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='نام کامل')),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='تلفن')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='ادرس')),
                ('city', models.CharField(blank=True, max_length=25, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=25, verbose_name='استان')),
                ('zipcode', models.CharField(blank=True, max_length=25, verbose_name='')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='شرح')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایلها',
            },
        ),
    ]
