# Generated by Django 5.2.1 on 2025-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.TextField(blank=True, max_length=250, verbose_name='ادرس'),
        ),
    ]
