# Generated by Django 5.2.1 on 2025-07-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_address2_alter_profile_address1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='address',
        ),
    ]
