# Generated by Django 5.2.1 on 2025-08-07 10:23

import cart.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_comment_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='کوپن')),
                ('code', models.CharField(max_length=20, verbose_name='کد تخفیف')),
                ('amount', models.CharField(choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('50', '50%')], default=0, max_length=20)),
                ('use', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپنها ',
            },
        ),
        migrations.CreateModel(
            name='FinalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=40, null=True, verbose_name='کاربر')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='اید سفارش')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کامل')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='ادرس')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شهر')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام استان')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کدپستی')),
                ('pay_way', models.CharField(choices=[('1', ' درگاه بانک ملت'), ('2', 'درگاه زرین پال'), ('3', 'درگاه بانک پاسارگاد'), ('4', 'هنگام دریافت')], max_length=40, verbose_name='روش پرداخت')),
                ('payed_way', models.CharField(choices=[('1', 'تی باکس'), ('2', 'پست'), ('3', 'چاپار'), ('4', 'باربری')], max_length=40, verbose_name='روش ارسال')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='هزینه پست')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نهای',
                'verbose_name_plural': 'نهایی',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اپدید شده در')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت ')),
                ('payment_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('send_status', models.BooleanField(default=False, verbose_name='وضعیت ارسال')),
                ('finaled', models.BooleanField(default=False, verbose_name='نهای شده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' کاربری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='', upload_to=cart.models.upload_image, verbose_name='تصویر')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('all_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.products')),
            ],
            options={
                'verbose_name': 'مقدار',
                'verbose_name_plural': ' سفارش',
            },
        ),
    ]
