# Generated by Django 5.2.1 on 2025-06-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingpayment',
            options={'verbose_name': 'اطلاعات شخصی', 'verbose_name_plural': 'مشخصات'},
        ),
    ]
