# Generated by Django 5.2.1 on 2025-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmodel',
            name='address2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ادرس دوم'),
        ),
    ]
