# Generated by Django 5.2.1 on 2025-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_shippingpayment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='کوپن')),
                ('code', models.CharField(max_length=20, verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپنها ',
            },
        ),
    ]
