# Generated by Django 5.2.1 on 2025-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_finalmodel_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'ثبت نام حساب کاربری'), ('2', 'تسویه حساب مهمان'), ('3', 'مشتری قبلی')], max_length=40, null=True, verbose_name='وضعیت کاربری'),
        ),
    ]
