# Generated by Django 5.2.1 on 2025-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_finalmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='use',
            field=models.BooleanField(default=False),
        ),
    ]
