# Generated by Django 5.1.6 on 2025-07-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmodel',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='finalmodel',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='finalmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='finalmodel',
            name='shipping_status',
        ),
        migrations.AddField(
            model_name='finalmodel',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام کامل'),
        ),
    ]
