# Generated by Django 5.2.1 on 2025-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.CharField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (50, '50%')], default='0%', max_length=20),
        ),
    ]
