# Generated by Django 5.1.6 on 2025-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_finalmodel_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کدپستی'),
        ),
    ]
