# Generated by Django 5.1.6 on 2025-07-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_finalmodel_city_alter_finalmodel_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmodel',
            name='status',
        ),
    ]
