# Generated by Django 5.1.6 on 2025-07-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_finalmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_status',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
