# Generated by Django 5.1.6 on 2025-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmodel',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send_status',
            field=models.BooleanField(default=False, verbose_name='وضعیت ارسال'),
        ),
    ]
